Maybe (check for x8664 Linux is untested).
git-svn-id: http://svn.clozure.com/publicsvn/openmcl/trunk/ccl@4015 8bdb8f1d-59ce-db11-9e41-0016172a54ae

diff --git a/scripts/openmcl64 b/scripts/openmcl64
--- a/scripts/openmcl64
+++ b/scripts/openmcl64
@@ -29,7 +29,18 @@ if [ -z "$OPENMCL_KERNEL" ]; then
     OPENMCL_KERNEL=dppccl64
     ;;
     Linux)
-    OPENMCL_KERNEL=ppccl64
+    case `arch` in
+      ppc64)
+      OPENMCL_KERNEL=ppccl64
+      ;;
+      x86_64)
+      OPENMCL_KERNEL=lx86cl64
+      ;;
+      *)
+      echo "Can't determine machine architecture.  Fix this."
+      exit 1
+      ;;
+    esac
     ;;
     *)
     echo "Can't determine host OS.  Fix this."
